# Site settings
name: 刘其宝 
email: liuqibao566@163.com
author: 刘其宝 
url: http://liuqibao.me
resume_site: http://liuqibao.me 
github: https://github.com/liuqb566
baseurl: ""
description: Good Good Study Go Go Up! 
meta_description: God!
motto: It's our wits that make us men.
banner: 学操千曲而后晓声，观千剑而后识器！

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: liuqb566
highlighter: rouge

# Build settings
markdown: kramdown

FB:
  comments :
    provider : duoshuo
    duoshuo:
        short_name : liuqibao 
    disqus :
        short_name : 
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light
gems:
  - jekyll-paginate
