# Site settings
name: Gossie's daily life
email: liuqibao566@163.com 
author: Gossie 
url: http://liuqibao.me
resume_site:                                               # set my resume dress 
github: https://github.com/liuqibao566
baseurl: ""
description: 好记性不如写博文！ 
meta_description:                                              # maybe appear in resume 
motto:                                                    # appear in head 
banner: 操千曲而后晓声，观千剑而后识器。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile','*.sh']

github_username: liuqibao566
highlighter: rouge

# Build settings
markdown: kramdown

FB:
  comments :
    provider : duoshuo
    duoshuo:
        short_name : Gossie
    disqus :
        short_name : 
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light
